name: 'Chat in Issue'
description: 'Use openai chat apis in github issues.'
inputs:
  token:
    description: 'Github token.'
    default: ${{ github.token }}
  openai-key:
    description: 'Openai API key, usually starts with "sk-".'
  model:
    description: 'Openai chat completion model.'
    default: 'gpt-3.5-turbo'
  issue-number:
    description: 'The created issue.'
    default: ${{ github.event.issue.number }}
  comment-id:
    description: 'The created comment.'
    default: ${{ github.event.comment.id }}
  prefix:
    description: |
      The issues/comments content should start with "$prefix" with format "/$prefix:".
      For example, if prefix is "chat", then only issues/comments start with "/chat:" would trigger a prompt.
      Multiple prefixes can be separated with comma.
      Please note that there are some built-in prefixes which you should not use:
        /ai-says: The responding message, will be used as a "role=assistant" message in prompts.
        /err:     Error messages. Issues/Comments start with this prefix will not be used as parts of the prompts.
        /system:  Will not trigger a prompt, but will be used as a "role=system" message.
      If a message contains string exactly "submit", this message itself will not be used as a part of the prompts.
    default: 'chat'
  user-whitelist:
    description: 'User whitelist, each line for one user regexp.'
    default: '.*'
  prompt-limit:
    description: |
      This configuration can be used in conjunction with `prompt-from-beginning-max`.

      Maximum character limit for prompt messages.

      If the total number of characters in the entire chat context does not exceed this value, all content will be used as prompt messages.
      Otherwise, the program will take up to `$prompt-from-tail-initial-max` characters starting from the end;
      then take up to `$prompt-from-beginning-max` characters starting from the front;
      finally, take up to `$prompt-limit` characters starting from the final position determined in the first step.

      If a message is truncated, the entire message will be discarded.
    default: '3000'
  prompt-from-tail-initial-max:
    description: 'Maximum characters length taken from the end of the conversation in the initial step and used in the prompt.'
    default: '0'
  prompt-from-beginning-max:
    description: 'Maximum characters length taken from the beginning of the conversation and used in the prompt.'
    default: '500'
  show-token-usage:
    description: 'Show OpenAI token usage in comments.'
    default: 'false'
  prompt-exclude-ai-response:
    description: |
      Exclude AI responses from prompt messages.
      A system message will be automatically added before the last message to distinguish the previous messages and the last message.
    default: 'false'
  trim-mode:
    description: |
      Defines the method of trimming the text.
      The following trim modes are supported:

      1. `normal`: Treats the entire text as a string and trims the leading and trailing whitespaces of the string.
      2. `none`: No trimming will be done.
      3. `each-line`: Trims the leading and trailing whitespaces of each line and deletes empty lines.
    default: 'normal'
runs:
  using: 'node16'
  main: 'compile/index.js'
branding:
  icon: 'message-circle'
  color: 'green'
